// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certs.sql

package storedb

import (
	"context"
	"time"
)

const getCertKeyByID = `-- name: GetCertKeyByID :one
SELECT cert_id, kek_tier, wrapped_dek, dek_nonce, cipher_nonce, ciphertext
FROM cert_keys
WHERE cert_id = ?
`

type GetCertKeyByIDRow struct {
	CertID      string
	KekTier     string
	WrappedDek  []byte
	DekNonce    []byte
	CipherNonce []byte
	Ciphertext  []byte
}

func (q *Queries) GetCertKeyByID(ctx context.Context, certID string) (GetCertKeyByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCertKeyByID, certID)
	var i GetCertKeyByIDRow
	err := row.Scan(
		&i.CertID,
		&i.KekTier,
		&i.WrappedDek,
		&i.DekNonce,
		&i.CipherNonce,
		&i.Ciphertext,
	)
	return i, err
}

const getCertificate = `-- name: GetCertificate :one
SELECT id, type, parent_id, serial_number,
       subject_cn, subject_o, subject_ou, subject_l, subject_st, subject_c,
       san_dns, san_ip, is_ca, path_len_constraint,
       key_algo, key_algo_params, key_usage, ext_key_usage,
       not_before, not_after, der_cert, fingerprint_sha256,
       status, revoked_at, revocation_reason, replaces_id, replaced_by_id, created_at
FROM certificates
WHERE id = ?
`

func (q *Queries) GetCertificate(ctx context.Context, id string) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertificate, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ParentID,
		&i.SerialNumber,
		&i.SubjectCn,
		&i.SubjectO,
		&i.SubjectOu,
		&i.SubjectL,
		&i.SubjectSt,
		&i.SubjectC,
		&i.SanDns,
		&i.SanIp,
		&i.IsCa,
		&i.PathLenConstraint,
		&i.KeyAlgo,
		&i.KeyAlgoParams,
		&i.KeyUsage,
		&i.ExtKeyUsage,
		&i.NotBefore,
		&i.NotAfter,
		&i.DerCert,
		&i.FingerprintSha256,
		&i.Status,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.ReplacesID,
		&i.ReplacedByID,
		&i.CreatedAt,
	)
	return i, err
}

const insertCertKey = `-- name: InsertCertKey :exec
INSERT INTO cert_keys (cert_id, kek_tier, wrapped_dek, dek_nonce, cipher_nonce, ciphertext)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertCertKeyParams struct {
	CertID      string
	KekTier     string
	WrappedDek  []byte
	DekNonce    []byte
	CipherNonce []byte
	Ciphertext  []byte
}

func (q *Queries) InsertCertKey(ctx context.Context, arg InsertCertKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertCertKey,
		arg.CertID,
		arg.KekTier,
		arg.WrappedDek,
		arg.DekNonce,
		arg.CipherNonce,
		arg.Ciphertext,
	)
	return err
}

const insertCertificate = `-- name: InsertCertificate :exec

INSERT INTO certificates (
    id, type, parent_id, serial_number,
    subject_cn, subject_o, subject_ou, subject_l, subject_st, subject_c,
    san_dns, san_ip, is_ca, path_len_constraint,
    key_algo, key_algo_params, key_usage, ext_key_usage,
    not_before, not_after, der_cert, fingerprint_sha256,
    status, replaces_id
) VALUES (?, ?, ?, ?,  ?, ?, ?, ?, ?, ?,  ?, ?, ?, ?,  ?, ?, ?, ?,  ?, ?, ?, ?,  ?, ?)
`

type InsertCertificateParams struct {
	ID                string
	Type              string
	ParentID          *string
	SerialNumber      string
	SubjectCn         string
	SubjectO          *string
	SubjectOu         *string
	SubjectL          *string
	SubjectSt         *string
	SubjectC          *string
	SanDns            string
	SanIp             string
	IsCa              int64
	PathLenConstraint *int64
	KeyAlgo           string
	KeyAlgoParams     *string
	KeyUsage          string
	ExtKeyUsage       string
	NotBefore         time.Time
	NotAfter          time.Time
	DerCert           []byte
	FingerprintSha256 string
	Status            string
	ReplacesID        *string
}

// Queries against the certificates and cert_keys tables. Backs internal/store/certs.go.
func (q *Queries) InsertCertificate(ctx context.Context, arg InsertCertificateParams) error {
	_, err := q.db.ExecContext(ctx, insertCertificate,
		arg.ID,
		arg.Type,
		arg.ParentID,
		arg.SerialNumber,
		arg.SubjectCn,
		arg.SubjectO,
		arg.SubjectOu,
		arg.SubjectL,
		arg.SubjectSt,
		arg.SubjectC,
		arg.SanDns,
		arg.SanIp,
		arg.IsCa,
		arg.PathLenConstraint,
		arg.KeyAlgo,
		arg.KeyAlgoParams,
		arg.KeyUsage,
		arg.ExtKeyUsage,
		arg.NotBefore,
		arg.NotAfter,
		arg.DerCert,
		arg.FingerprintSha256,
		arg.Status,
		arg.ReplacesID,
	)
	return err
}

const listCAs = `-- name: ListCAs :many
SELECT id FROM certificates
WHERE type IN ('root_ca', 'intermediate_ca')
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListCAs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCAs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertKeyWraps = `-- name: ListCertKeyWraps :many
SELECT cert_id, wrapped_dek, dek_nonce
FROM cert_keys
ORDER BY cert_id
`

type ListCertKeyWrapsRow struct {
	CertID     string
	WrappedDek []byte
	DekNonce   []byte
}

func (q *Queries) ListCertKeyWraps(ctx context.Context) ([]ListCertKeyWrapsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCertKeyWraps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertKeyWrapsRow{}
	for rows.Next() {
		var i ListCertKeyWrapsRow
		if err := rows.Scan(&i.CertID, &i.WrappedDek, &i.DekNonce); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaves = `-- name: ListLeaves :many
SELECT id FROM certificates
WHERE type = 'leaf'
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListLeaves(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLeaves)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevokedChildren = `-- name: ListRevokedChildren :many
SELECT serial_number, revoked_at, COALESCE(revocation_reason, 0) AS reason_code
FROM certificates
WHERE parent_id = ?
  AND status = 'revoked'
  AND not_after > datetime('now')
ORDER BY revoked_at
`

type ListRevokedChildrenRow struct {
	SerialNumber string
	RevokedAt    *time.Time
	ReasonCode   int64
}

func (q *Queries) ListRevokedChildren(ctx context.Context, parentID *string) ([]ListRevokedChildrenRow, error) {
	rows, err := q.db.QueryContext(ctx, listRevokedChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRevokedChildrenRow{}
	for rows.Next() {
		var i ListRevokedChildrenRow
		if err := rows.Scan(&i.SerialNumber, &i.RevokedAt, &i.ReasonCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCertRevoked = `-- name: MarkCertRevoked :execrows
UPDATE certificates
   SET status = 'revoked', revoked_at = ?, revocation_reason = ?
   WHERE id = ? AND status != 'revoked'
`

type MarkCertRevokedParams struct {
	RevokedAt        *time.Time
	RevocationReason *int64
	ID               string
}

func (q *Queries) MarkCertRevoked(ctx context.Context, arg MarkCertRevokedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markCertRevoked, arg.RevokedAt, arg.RevocationReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const supersedeCert = `-- name: SupersedeCert :execrows
UPDATE certificates
   SET status = 'superseded', replaced_by_id = ?
   WHERE id = ? AND status = 'active'
`

type SupersedeCertParams struct {
	ReplacedByID *string
	ID           string
}

func (q *Queries) SupersedeCert(ctx context.Context, arg SupersedeCertParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, supersedeCert, arg.ReplacedByID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCertKeyWrap = `-- name: UpdateCertKeyWrap :execrows
UPDATE cert_keys
   SET wrapped_dek = ?, dek_nonce = ?
   WHERE cert_id = ?
`

type UpdateCertKeyWrapParams struct {
	WrappedDek []byte
	DekNonce   []byte
	CertID     string
}

func (q *Queries) UpdateCertKeyWrap(ctx context.Context, arg UpdateCertKeyWrapParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCertKeyWrap, arg.WrappedDek, arg.DekNonce, arg.CertID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
