// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crls.sql

package storedb

import (
	"context"
	"time"
)

const getLatestCRL = `-- name: GetLatestCRL :one
SELECT issuer_cert_id, crl_number, this_update, next_update, der, updated_at
FROM crls
WHERE issuer_cert_id = ?
ORDER BY crl_number DESC
LIMIT 1
`

func (q *Queries) GetLatestCRL(ctx context.Context, issuerCertID string) (Crl, error) {
	row := q.db.QueryRowContext(ctx, getLatestCRL, issuerCertID)
	var i Crl
	err := row.Scan(
		&i.IssuerCertID,
		&i.CrlNumber,
		&i.ThisUpdate,
		&i.NextUpdate,
		&i.Der,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCRL = `-- name: InsertCRL :exec

INSERT INTO crls (issuer_cert_id, crl_number, this_update, next_update, der, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertCRLParams struct {
	IssuerCertID string
	CrlNumber    int64
	ThisUpdate   time.Time
	NextUpdate   time.Time
	Der          []byte
	UpdatedAt    time.Time
}

// Queries against the crls table. Backs internal/store/crls.go.
func (q *Queries) InsertCRL(ctx context.Context, arg InsertCRLParams) error {
	_, err := q.db.ExecContext(ctx, insertCRL,
		arg.IssuerCertID,
		arg.CrlNumber,
		arg.ThisUpdate,
		arg.NextUpdate,
		arg.Der,
		arg.UpdatedAt,
	)
	return err
}

const nextCRLNumber = `-- name: NextCRLNumber :one
SELECT MAX(crl_number) FROM crls WHERE issuer_cert_id = ?
`

func (q *Queries) NextCRLNumber(ctx context.Context, issuerCertID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, nextCRLNumber, issuerCertID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}
