// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package storedb

import (
	"context"
	"time"
)

const deleteExpiredIdemTokens = `-- name: DeleteExpiredIdemTokens :execrows
DELETE FROM idempotency_tokens WHERE expires_at <= datetime('now')
`

func (q *Queries) DeleteExpiredIdemTokens(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredIdemTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getIdemToken = `-- name: GetIdemToken :one
SELECT token, created_at, used_at, result_url, expires_at
FROM idempotency_tokens
WHERE token = ? AND expires_at > datetime('now')
`

func (q *Queries) GetIdemToken(ctx context.Context, token string) (IdempotencyToken, error) {
	row := q.db.QueryRowContext(ctx, getIdemToken, token)
	var i IdempotencyToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UsedAt,
		&i.ResultUrl,
		&i.ExpiresAt,
	)
	return i, err
}

const insertIdemToken = `-- name: InsertIdemToken :exec

INSERT INTO idempotency_tokens (token, created_at, expires_at)
VALUES (?, ?, ?)
`

type InsertIdemTokenParams struct {
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
}

// Queries against the idempotency_tokens table. Backs internal/store/idempotency.go.
func (q *Queries) InsertIdemToken(ctx context.Context, arg InsertIdemTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertIdemToken, arg.Token, arg.CreatedAt, arg.ExpiresAt)
	return err
}

const markIdemTokenUsed = `-- name: MarkIdemTokenUsed :execrows
UPDATE idempotency_tokens
   SET used_at = datetime('now'), result_url = ?
   WHERE token = ? AND used_at IS NULL
`

type MarkIdemTokenUsedParams struct {
	ResultUrl *string
	Token     string
}

func (q *Queries) MarkIdemTokenUsed(ctx context.Context, arg MarkIdemTokenUsedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markIdemTokenUsed, arg.ResultUrl, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
