// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"time"
)

type CertKey struct {
	CertID      string
	KekTier     string
	WrappedDek  []byte
	DekNonce    []byte
	CipherNonce []byte
	Ciphertext  []byte
	CreatedAt   time.Time
}

type Certificate struct {
	ID                string
	Type              string
	ParentID          *string
	SerialNumber      string
	SubjectCn         string
	SubjectO          *string
	SubjectOu         *string
	SubjectL          *string
	SubjectSt         *string
	SubjectC          *string
	SanDns            string
	SanIp             string
	IsCa              int64
	PathLenConstraint *int64
	KeyAlgo           string
	KeyAlgoParams     *string
	KeyUsage          string
	ExtKeyUsage       string
	NotBefore         time.Time
	NotAfter          time.Time
	DerCert           []byte
	FingerprintSha256 string
	Status            string
	RevokedAt         *time.Time
	RevocationReason  *int64
	ReplacesID        *string
	ReplacedByID      *string
	CreatedAt         time.Time
}

type Crl struct {
	IssuerCertID string
	CrlNumber    int64
	ThisUpdate   time.Time
	NextUpdate   time.Time
	Der          []byte
	UpdatedAt    time.Time
}

type DeployTarget struct {
	ID                 string
	CertID             string
	Name               string
	CertPath           string
	KeyPath            string
	ChainPath          *string
	Mode               string
	Owner              *string
	Group              *string
	PostCommand        *string
	AutoOnRotate       int64
	LastDeployedAt     *time.Time
	LastDeployedSerial *string
	LastStatus         *string
	LastError          *string
	CreatedAt          time.Time
}

type IdempotencyToken struct {
	Token     string
	CreatedAt time.Time
	UsedAt    *time.Time
	ResultUrl *string
	ExpiresAt time.Time
}

type Setting struct {
	Key       string
	Value     []byte
	UpdatedAt time.Time
}
