// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package storedb

import (
	"context"
)

const getSetting = `-- name: GetSetting :one

SELECT value FROM settings WHERE key = ?
`

// Queries against the settings table. Backs internal/store/settings.go.
func (q *Queries) GetSetting(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value, updated_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT(key) DO UPDATE
  SET value      = excluded.value,
      updated_at = excluded.updated_at
`

type UpsertSettingParams struct {
	Key   string
	Value []byte
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
